version: '3'

services:
  container:
    image: node:current-alpine
    container_name: mournfullys-chrome-extension
    working_dir: /usr/src/app
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.parcel-cache
    command: npm run start
