version: '3'

services:
  container:
    image: node:current-alpine
    container_name: mournfully-extension
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production # or 'development'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
